# latexmk configuration for Springer SN (pdflatex + bibtex)
$pdf_mode = 1;
$bibtex = 'bibtex %O %B';
$clean_ext = 'acn acr alg aux bbl bcf blg fdb_latexmk fls lof log lot out run.xml synctex.gz toc';
