name: build-paper
on: [push]
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
      - name: Build PDF
        run: |
          cd paper_model
          latexmk -pdf -silent main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: paperI_pdf
          path: paper_model/main.pdf
       
          python-tests:
  
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run demo
        run: python code/demo_run.py