name: build-paper
on: [push]
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
      - name: Build PDF
        run: |
          cd paper_model
          latexmk -pdf -silent main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: paperI_pdf
          path: paper_model/main.pdf