name: neurofractal
channels:
  - conda-forge
  - r
dependencies:
  # Conda packages
  - python=3.11
  - r-base=4.3
  - r-metafor
  - r-robumeta
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - seaborn

  # Pip subsection (must be nested)
  - pip:
    - git+https://github.com/rayyanqcri/rayyan-client.git